server:
  port: 8083

spring:
  application:
    name: notification-service
  # kafka consumer properties
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.theshy.microservices.order.event.OrderPlacedEvent

  # mail properties
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 4225c3e754bca4
    password: 39c85b1325e322

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  # loki properties
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: notification-service
  tracing:
    sampling:
      probability: 1.0 # send 100% of the traces it generates to Tempo

# Loki url
loki:
  url: http://localhost:3100/loki/api/v1/push
