spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/product-service?authSource=admin

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  # loki properties
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: product-service
  tracing:
    sampling:
      probability: 1.0 # send 100% of the traces it generates to Tempo

# Loki url
loki:
  url: http://localhost:3100/loki/api/v1/push
